//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace membakery_inventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        internal string LoginErrorMessage;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Transactions = new HashSet<Transaction>();
            this.TransactionIns = new HashSet<TransactionIn>();
        }
    
        public int Emp_ID { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string no_acc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionIn> TransactionIns { get; set; }
    }
}
