//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace membakery_inventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionNo { get; set; }
        public int Emp_ID { get; set; }
        public int Stock_ID { get; set; }
        public Nullable<int> TQuantity { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
